services:
- type: web
  name: pryMongoEsp32
  runtime: python
  repo: https://github.com/JohannVC834/pryMongoEsp32.git
  plan: free
  envVars:
  - key: MONGO_URI
    value: mongodb+srv://johann12032005:Gt6Y2WNDmiVJOFef@cluster0.rc46fht.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python app.py
version: "1"